name: Publish timestamp build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call_workflow:
    name: Run Central Publish Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/central-publish-template.yml@main
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
